#pragma once
#define NOMINMAX
#include <vector>
#include <string>
#include <sstream>
#include <stack>
#include <map>
#include <ext/hash_map>
#include <algorithm>
#include <limits>
#include <ctime>
#include <iostream>
#include <fstream>
#include <cassert>
